import sys
sys.path.append("./")

import numpy as np

from robot.robot.base_robot import Robot

from robot.controller.Y1_controller import Y1Controller
from robot.sensor.Cv_sensor import CvSensor
from robot.sensor.V4l2_sensor import V4l2Sensor

from robot.data.collect_any import CollectAny
from robot.utils.base.data_transform_pipeline import X_one_format_pipeline
from robot.utils.base.data_handler import is_enter_pressed
import time

# setting your realsense serial
# Based on v4l2-ctl output, your cameras are at indices 0, 2, and 4.
# Please check the images generated by tools/check_camera_indices.py to assign correctly.
CAMERA_SERIALS = {
    'head': "/dev/video0",        # Candidate index
    'left_wrist': "/dev/video2",  # Candidate index
    'right_wrist': "/dev/video4", # Candidate index
}

# Define start position (in degrees)
START_POSITION_ANGLE_LEFT_ARM = [
    0,   # Joint 1
    0,    # Joint 2
    0,  # Joint 3
    0,   # Joint 4
    0,  # Joint 5
    0,    # Joint 6
]

# Define start position (in degrees)
START_POSITION_ANGLE_RIGHT_ARM = [
    0,   # Joint 1
    0,    # Joint 2
    0,  # Joint 3
    0,   # Joint 4
    0,  # Joint 5
    0,    # Joint 6
]

condition = {
    "save_path": "./save/",
    "task_name": "new",
    "save_format": "hdf5",
    "save_freq": 10, 
}

class XsparkRobot(Robot):
    def __init__(self, condition=condition, move_check=True, start_episode=0):
        super().__init__(condition=condition, move_check=move_check, start_episode=start_episode)
        self.first_start = True
        self.controllers = {
            "arm":{
                "left_arm": Y1Controller("left_arm"),
                "right_arm": Y1Controller("right_arm"),
            },
        }
        self.sensors = {
            "image": {
                "cam_head": V4l2Sensor("cam_head"), # CvSensor
                "cam_left_wrist": V4l2Sensor("cam_left_wrist"),
                "cam_right_wrist": V4l2Sensor("cam_right_wrist"),
            },
        }
        # self.collection._add_data_transform_pipeline(X_one_format_pipeline)

    def set_up(self, teleop=False):
        super().set_up()
        self.teleop_mode=teleop
        self.controllers["arm"]["left_arm"].set_up("can1", teleop=teleop)
        self.controllers["arm"]["right_arm"].set_up("can0", teleop=teleop)

        self.sensors["image"]["cam_head"].set_up(CAMERA_SERIALS['head'], is_depth=False, is_jepg=True)
        self.sensors["image"]["cam_left_wrist"].set_up(CAMERA_SERIALS['left_wrist'], is_depth=False, is_jepg=True)
        self.sensors["image"]["cam_right_wrist"].set_up(CAMERA_SERIALS['right_wrist'], is_depth=False, is_jepg=True)
        
        self.set_collect_type({"arm": ["joint","qpos","gripper"],
                                "image": ["color"]
                               })
        print("set up success!")

    def reload_cameras(self):
        try:
            """Cleanup existing camera devices"""
            self.sensors["image"]["cam_head"].cleanup()
            self.sensors["image"]["cam_left_wrist"].cleanup()
            self.sensors["image"]["cam_right_wrist"].cleanup()
            print("Cleaning up existing cameras done.")

            """Reload camera devices"""
            self.sensors["image"]["cam_head"].set_up(CAMERA_SERIALS['head'], is_depth=False, is_jepg=True)
            self.sensors["image"]["cam_left_wrist"].set_up(CAMERA_SERIALS['left_wrist'], is_depth=False, is_jepg=True)
            self.sensors["image"]["cam_right_wrist"].set_up(CAMERA_SERIALS['right_wrist'], is_depth=False, is_jepg=True)
            print("Cameras reloaded successfully.")
        except Exception as e:
            print(f"Error reloading cameras: {str(e)}")

    def reset(self):
        if self.teleop_mode:
            self.change_mode(teleop=False)
        time.sleep(2)
        move_data = {
            "arm":{
                "left_arm":{
                    # "joint": [0, 0, 0.3, 0.2, 0, 0],
                    "joint": [0, 0, 0, 0, 0, 0],
                    "gripper":  1.0,
                },
                
                "right_arm":{
                    # "joint": [0, 0, 0.3, 0.2, 0, 0],
                    "joint": [0, 0, 0, 0, 0, 0],
                    "gripper":  1.0,
                }
            }
        }
        self.move(move_data)
        time.sleep(5)
        if self.teleop_mode:
            self.change_mode(teleop=True)
    
    # ======================== EXTRA ======================== #
    def change_mode(self, teleop):
        time.sleep(1)
        self.controllers["arm"]["left_arm"].change_mode(teleop)
        time.sleep(1)
        self.controllers["arm"]["right_arm"].change_mode(teleop)
        time.sleep(1)
    
    def set_map(self, map_path):
        self.controllers["mobile"]["slamware"].set_map(map_path)

if __name__ == "__main__":
    import time
    
    robot = XsparkRobot(move_check=False)
    robot.set_up(teleop=False)
    robot.reset()
    robot.replay(data_path="./save/new/0.hdf5", key_banned=["qpos"], is_collect=True, episode_id=1)